### PR TITLE
touch a file

### PR DESCRIPTION
**Pull request by otan**

### CODE REVIEW

**Comment by otan** [comment]
Hello external contributor! I am Blathers and I am here to assist you get your PR merged. If this is your first PR, please make sure you have read [this guide to creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

Before we can accept your PR, please review the following recommendations: 
 * Please ensure your git commit message contains a [release note](https://wiki.crdb.io/wiki/spaces/CRDB/pages/186548364/Release+notes).
 * Please ensure your pull request description contains a [release note](https://wiki.crdb.io/wiki/spaces/CRDB/pages/186548364/Release+notes) - this can be the same as the one in your commit message.

We were unable to automatically find a reviewer for your issue. You can try CCing one of the following members:
* A person you worked with closely on this PR.
* The person who created the ticket, or a CRDB organization member involved with the ticket.
* Join our [community slack channel](https://cockroa.ch/slack) and ask on #contributors.
* You can find members of the CockroachDB organization [here](https://github.com/orgs/cockroachdb/people).

NOTE: I am experimental.

**Comment by otan** [comment]
Hello external contributor! I am Blathers and I am here to assist you get your PR merged. If this is your first PR, please make sure you have read [this guide to creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

Before we can accept your PR, please review the following recommendations: 
 * Please ensure your git commit message contains a [release note](https://wiki.crdb.io/wiki/spaces/CRDB/pages/186548364/Release+notes).
 * Please ensure your pull request description contains a [release note](https://wiki.crdb.io/wiki/spaces/CRDB/pages/186548364/Release+notes) - this can be the same as the one in your commit message.

We were unable to automatically find a reviewer for your issue. You can try CCing one of the following members:
* A person you worked with closely on this PR.
* The person who created the ticket, or a CRDB organization member involved with the ticket.
* Join our [community slack channel](https://cockroa.ch/slack) and ask on #contributors.
* You can find members of the CockroachDB organization [here](https://github.com/orgs/cockroachdb/people).

NOTE: I am experimental.

**Comment by otan** [comment]
@knz you usually are on top of stuff when external contributors miss something! i'm tryign to make a bot that automagically detects for any issues from external contributor commits + tries to auto assign a reviewer (haven't done that part yet).

anything else i should add when people submit a PR?

here are the checks so far: https://github.com/otan-cockroach/blathers-bot/blob/master/main.py#L115

(don't judge the spaghetti)

**Comment by knz** [comment]
Thanks oliver for picking this up.

I have not yet reviewed your code (I could, if you ask me) but there's some things that spring to mind: 

- re https://github.com/otan-cockroach/blathers-bot/blob/master/main.py#L93

  given how often the services we rely on have transient faults, I am very surprised your code has no logging, no "internal error" reports, no sentry calls etc -- all the things by which we'd know something went awry.

- re https://github.com/otan-cockroach/blathers-bot/blob/master/main.py#L148

  there are more checks on the release note possible. the real question is "how far do we want to go" -- what's your opinion on this? what did you have in mind?

- re https://github.com/otan-cockroach/blathers-bot/blob/master/main.py#L129

  how is this "first time contributor" boolean known?

**Comment by otan** [comment]
With logging, what I've got right now works with my basic "I don't know
what I'm doing" setup onGCP, which also gives me my logs automatically if
there's an error thanks to using cloud functions.

I think ideally the release note stuff should be in CI, and bathers should
catch stuff that's generally fuzzy from a non CI pov. That said I'm curious
what kind of checks you're thinking about.

Github does the calculation of first time contributor. I've seen the PR
page have flashy labels when people submit their PR for the first time,
it's cool their API supports this. Have no idea about how it ranks priority
wise internally though. See
https://developer.github.com/v4/enum/commentauthorassociation/.

Planning to rewrite this in go maybe next week so don't worry about
reviewing it, heh. Just curious about your thoughts on what else we could
do.

**Pull request closed without merging**
